Repository pckv/repost-fastapi, pull requests merged in 2020-02, with the labels that each got.

#8 Create public schemas for all endpoints and define all /users endpoints
  repost/api/routes/users.py
  repost/api/schemas/__init__.py
  repost/api/schemas/comment.py
  repost/api/schemas/post.py
  repost/api/schemas/resub.py
  repost/api/schemas/user.py
  repost/main.py
Labels: documentation, enhancement

#9 Add OAuth2 skeleton and document users endpoint responses
  repost/api/api.py
  repost/api/routes/auth.py
  repost/api/routes/users.py
  repost/api/schemas/__init__.py
  repost/api/schemas/auth.py
  repost/api/schemas/error.py
  repost/api/security.py
Labels: documentation, enhancement

#13 Change endpoint responses and implement edit user endpoint
  repost/api/routes/posts.py
  repost/api/routes/resubs.py
  repost/api/routes/users.py
  repost/api/schemas/__init__.py
  repost/api/schemas/user.py
Labels: documentation

#16 Improve documentation and fix parent relations in comment and post schemas
  repost/api/api.py
  repost/api/resolvers.py
  repost/api/routes/auth.py
  repost/api/routes/comments.py
  repost/api/routes/posts.py
  repost/api/routes/resubs.py
  repost/api/routes/users.py
  repost/api/schemas/__init__.py
  repost/api/schemas/auth.py
  repost/api/schemas/comment.py
  repost/api/schemas/error.py
  repost/api/schemas/generic.py
  repost/api/schemas/post.py
  repost/api/schemas/resub.py
  repost/api/schemas/user.py
  repost/api/security.py
  repost/main.py
Labels: bug, documentation, enhancement

#31 Implement bcrypt hashing functions using passlib
  repost/password.py
  requirements.txt
Labels: enhancement

#32 Add JSON Web Token creation and validation
  repost/api/security.py
  repost/main.py
  requirements.txt
Labels: enhancement

#33 First draft of Database Models and Engine
  repost/api/schemas/comment.py
  repost/api/schemas/post.py
  repost/api/schemas/resub.py
  repost/database.py
  repost/main.py
  repost/models/__init__.py
  repost/models/comment.py
  repost/models/post.py
  repost/models/resub.py
  repost/models/user.py
  repost/models/votes.py
  requirements.txt
Labels: enhancement

#35 Create a universal config instance using dotenv
  .gitignore
  repost/__init__.py
  repost/api/security.py
  repost/config.py
  repost/main.py
Labels: enhancement

#37 Add a config to database URL and handle SQLite driver configuration
  .gitignore
  repost/config.py
  repost/database.py
Labels: enhancement

#36 Change schema to use name and models to use id
  repost/api/schemas/comment.py
  repost/api/schemas/post.py
  repost/api/schemas/resub.py
  repost/models/comment.py
  repost/models/post.py
Labels: database

#43 Add app to __init__.py for more sensible startup
  repost/__init__.py
Labels: enhancement

#41 Implement and use crud for posts endpoints
  repost/api/resolvers.py
  repost/api/routes/posts.py
  repost/api/schemas/post.py
  repost/api/schemas/resub.py
  repost/api/schemas/user.py
  repost/crud/__init__.py
  repost/crud/posts.py
  repost/crud/resubs.py
  repost/models/comment.py
  repost/models/post.py
  repost/models/resub.py
  repost/models/user.py
Labels: database, enhancement

#48 Add correct responses to all endpoints
  repost/api/routes/auth.py
  repost/api/routes/comments.py
  repost/api/routes/posts.py
  repost/api/routes/resubs.py
  repost/api/routes/users.py
  repost/api/security.py
Labels: bug, documentation

#51 Implement crud and endpoint to get resubs, posts and comments by user
  repost/api/routes/users.py
  repost/crud/__init__.py
  repost/crud/users.py
Labels: database, enhancement

#50 Check that created user and resub don't exist
  repost/api/routes/resubs.py
  repost/api/routes/users.py
Labels: bug

#52 Change all create endpoints to use HTTP status code `201 Created`
  repost/api/routes/auth.py
  repost/api/routes/comments.py
  repost/api/routes/posts.py
  repost/api/routes/resubs.py
Labels: bug, documentation

#55 Communication allowance with front-end
  repost/main.py
Labels: enhancement

#53 Create a custom endpoint for replies that stays consistent with the API
  repost/api/routes/comments.py
Labels: bug, enhancement

#56 Fix possibility to set "optional but can't be null" fields in edit endpoints
  repost/api/schemas/comment.py
  repost/api/schemas/post.py
Labels: bug
